// src/components/map-leaflet.svelte
<script>
  import { onMount, onDestroy } from "svelte";
  import L from "leaflet";
  import "leaflet.markercluster";
  import "leaflet.markercluster/dist/MarkerCluster.css";
  import "leaflet.markercluster/dist/MarkerCluster.Default.css";
  import "leaflet/dist/leaflet.css";

  import { withBasePath } from "@/lib/withBasePath";

  /* ---------- props ---------- */
  export let geoJsonData;
  export let className = "w-full h-64 md:h-96 border rounded z-10";
  export let initialView = [50, 10];
  export let initialZoom = 3;
  export let markerColor = "#B42222";
  export let filterMode = "single"; // "single" | "dual"

  let mapEl;
  let map;
  let authorLayer;
  let libraryLayer;
  let cleanupResize;
  	
  /* ---------- icons ---------- */
  const pinGreen = new URL("@/icons/map-pin-green.svg", import.meta.url).toString();
  const pinRed = new URL("@/icons/map-pin-red.svg", import.meta.url).toString();
  const pin = new URL("@/icons/map-pin.png", import.meta.url).toString();

  const authorIcon = L.icon({
    iconUrl: pinRed,
    iconSize: [25, 25],
    iconAnchor: [12, 41],
    popupAnchor: [0, -41],
  });

  const libraryIcon = L.icon({
    iconUrl: pinGreen,
    iconSize: [25, 25],
    iconAnchor: [12, 41],
    popupAnchor: [0, -41],
  });

  const defaultIcon = L.icon({
    iconUrl: pin,
    iconSize: [25, 25],
    iconAnchor: [12, 41],
    popupAnchor: [0, -41],
  });

  L.Marker.prototype.options.icon = defaultIcon;

  /* ---------- marker updates ---------- */
  function updateMapMarkers(dataToShow) {
    if (!map || !dataToShow?.features) return;

    authorLayer.clearLayers();
    libraryLayer.clearLayers();

    dataToShow.features.forEach((feature) => {
      const { geometry, properties } = feature;
      if (
        geometry?.type === "Point" &&
        geometry.coordinates?.length === 2 &&
        !isNaN(geometry.coordinates[0]) &&
        !isNaN(geometry.coordinates[1])
      ) {
        const type = properties?.type || "author";

        const marker = L.marker(
          [geometry.coordinates[1], geometry.coordinates[0]],
          {
            icon: type === "author" ? authorIcon : libraryIcon,
          }
        );

        if (properties) {
          const url = withBasePath(properties.url || "");
          marker.bindPopup(`
            <div class="map-popup">
              <h3>
                <a href="${url}" class="font-semibold text-base underline decoration-dotted underline-offset-2">
                  ${properties.title || ""}
                </a>
              </h3>
              <p>
                Place: ${properties.place || ""} (${properties.description || ""})<br/>
                ${properties.author ? `Author: ${properties.author}<br/>` : ""}
                ${properties.work ? `Work: ${properties.work}<br/>` : ""}
                ${properties.manuscript ? `MS: ${properties.manuscript}<br/>` : ""}
              </p>
            </div>
          `);
        }

        type === "author"
          ? authorLayer.addLayer(marker)
          : libraryLayer.addLayer(marker);
      }
    });

    // Fit bounds
    const coords = dataToShow.features
      .filter((f) => f.geometry?.type === "Point")
      .map((f) => [f.geometry.coordinates[1], f.geometry.coordinates[0]]);

    if (coords.length) {
      map.fitBounds(L.latLngBounds(coords), {
        padding: [50, 50],
        maxZoom: 10,
      });
    }
  }

  /* ---------- external API for Tabulator ---------- */
  $: if (geoJsonData) {
    window.updateMapWithFilteredIds = (filteredIds) => {
      if (!geoJsonData?.features) return;

      let filteredGeoJson;

      if (filterMode === "dual") {
        filteredGeoJson = {
          type: "FeatureCollection",
          features: geoJsonData.features.filter((f) => {
            if (!f.properties) return false;
            if (f.properties.type === "author") {
              return filteredIds.includes(f.properties.aut_jad_id);
            }
            if (f.properties.type === "library") {
              return filteredIds.includes(f.properties.ms_jad_id);
            }
            return false;
          }),
        };
      } else {
        filteredGeoJson = {
          type: "FeatureCollection",
          features: geoJsonData.features.filter(
            (f) => filteredIds.includes(f.properties?.jad_id)
          ),
        };
      }

      updateMapMarkers(filteredGeoJson);
    };
  }



	let resizeHandle;

  /* ---------- lifecycle ---------- */
  onMount(() => {
    map = L.map(mapEl).setView(initialView, initialZoom);

    L.tileLayer(
      "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
      {
        attribution:
          '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
        maxZoom: 19,
      }
    ).addTo(map);

    authorLayer = L.markerClusterGroup({
      maxClusterRadius: 50,
      iconCreateFunction: (cluster) =>
        L.divIcon({
          html: `<div class="bg-brand-800 opacity-60 text-white rounded-full w-8 h-8 flex items-center justify-center">${cluster.getChildCount()}</div>`,
          className: "custom-cluster-icon-origin",
          iconSize: [30, 30],
        }),
    });

    libraryLayer = L.markerClusterGroup({
      maxClusterRadius: 50,
      iconCreateFunction: (cluster) =>
        L.divIcon({
          html: `<div class="bg-sage-900 opacity-60 text-white rounded-full w-8 h-8 flex items-center justify-center">${cluster.getChildCount()}</div>`,
          className: "custom-cluster-icon-origin",
          iconSize: [30, 30],
        }),
    });

    map.addLayer(authorLayer);
    map.addLayer(libraryLayer);

    if (geoJsonData?.features) {
      const hasAuthor = geoJsonData.features.some(
        (f) => f.properties?.type === "author"
      );
      const hasLibrary = geoJsonData.features.some(
        (f) => f.properties?.type === "library"
      );

      if (hasAuthor && hasLibrary) {
         L.control
          .layers(
            {},
            {
              '<span class="layer-authors">Authors</span>': authorLayer,
              '<span class="layer-manuscripts">Manuscripts</span>':
                libraryLayer,
            },
            { collapsed: false },
          )
          .addTo(map);
      }

      updateMapMarkers(geoJsonData);
    }
  

  cleanupResize = enableVerticalResize(mapEl, map, resizeHandle);
});
onDestroy(() => {
	if (cleanupResize) cleanupResize();
	if (map) map.remove();
});

  // helpers
  function enableVerticalResize(mapEl, map, handle) {
			let startY;
			let startHeight;

			const onMouseMove = (e) => {
				const newHeight = startHeight + (e.clientY - startY);
				mapEl.style.height = `${Math.max(newHeight, 200)}px`;
				map.invalidateSize();
			};

			const onMouseUp = () => {
				document.removeEventListener("pointermove", onMouseMove);
				document.removeEventListener("pointerup", onMouseUp);
			};

			const onMouseDown = (e) => {
				startY = e.clientY;
				startHeight = mapEl.offsetHeight;

				document.addEventListener("pointermove", onMouseMove);
				document.addEventListener("pointerup", onMouseUp);
			};

			handle.addEventListener("pointerdown", onMouseDown);

			return () => {
				handle.removeEventListener("pointerdown", onMouseDown);
				document.removeEventListener("pointermove", onMouseMove);
				document.removeEventListener("pointerup", onMouseUp);
			};
}
</script>

<div class="flex flex-col w-full">
	<div bind:this={mapEl} class={className} id="leaflet-map"></div>
	<!-- Drag handle -->
	<div
		bind:this={resizeHandle}
		class="hidden md:flex items-center justify-center h-6 cursor-row-resize py-4 bg-neutral-400 active:bg-brand-500 text-brand-50 select-none"
		title="Kartenhöhe ändern"
		aria-label="Kartenhöhe ändern"
	>
		<svg xmlns="http://www.w3.org/2000/svg" 
			width="24" height="24" 
			viewBox="0 0 24 24" fill="none" stroke="currentColor" 
			stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
			<path d="m16 16-4 4-4-4"/>
			<path d="M3 12h18"/>
			<path d="m8 8 4-4 4 4"/>
		</svg>
	</div>
  <div class="text-brand-800 italic text-sm text-end"><span class="font-bold">NB:</span> Only entries with geographic coordinates are displayed on the map.</div>

</div>

// src/components/map-leaflet.jsx
import { useEffect, useRef } from "react";
import L from "leaflet";
import "leaflet.markercluster";
import "leaflet.markercluster/dist/MarkerCluster.css";
import "leaflet.markercluster/dist/MarkerCluster.Default.css";
import "leaflet/dist/leaflet.css";
import { withBasePath } from "@/lib/withBasePath";

// Create custom icon
const pinGreen = new URL(
  "@/icons/map-pin-green.png",
  import.meta.url
).toString();
const pinRed = new URL("@/icons/map-pin-red.png", import.meta.url).toString();
const pin = new URL("@/icons/map-pin.png", import.meta.url).toString();

const authorIcon = L.icon({
  iconUrl: pinRed, // Use the same pin image
  iconSize: [25, 25], // Adjust size as needed
  iconAnchor: [12, 41], // Point of the icon which will correspond to marker's location
  popupAnchor: [0, -41], // Point from which the popup should open relative to the iconAnchor
});

const libraryIcon = L.icon({
  iconUrl: pinGreen, // Use the same pin image
  iconSize: [25, 25], // Adjust size as needed
  iconAnchor: [12, 41], // Point of the icon which will correspond to marker's location
  popupAnchor: [0, -41], // Point from which the popup should open relative to the iconAnchor
});
const customIcon = L.icon({
  iconUrl: pin,
  iconSize: [25, 25], // size of the icon, adjust as needed
  iconAnchor: [12, 41], // point of the icon which will correspond to marker's location
  popupAnchor: [0, -41], // point from which the popup should open relative to the iconAnchor
});

// Set as default icon
L.Marker.prototype.options.icon = customIcon;

export default function LeafletMap({
  geoJsonData,
  className = "w-full h-64 md:h-96 border rounded z-10",
  initialView = [50, 10],
  initialZoom = 3,
  markerColor = "#B42222",
}) {
  const mapRef = useRef(null);
  const mapInstanceRef = useRef(null);
  const markersRef = useRef(null);
  const authorLayerRef = useRef(null);
  const libraryLayerRef = useRef(null);

  // Create a method that can be called from outside to update the map
  useEffect(() => {
    // Make the updateMap function available globally to be called in tabulator by table.on filter
    window.updateMapWithFilteredIds = (filteredIds) => {
      if (!geoJsonData || !geoJsonData.features) return;

      // Filter the geoJsonData to only include features with matching jad_ids
      // Since table sends ms_transmission jad_ids, we need to check against those
      const filteredGeoJson = {
        type: "FeatureCollection",
        features: geoJsonData.features.filter(
          (feature) =>
            feature.properties &&
            filteredIds.includes(feature.properties.jad_id)
        ),
      };

      updateMapMarkers(filteredGeoJson);
    };

    return () => {
      // Clean up the global function when component unmounts
      delete window.updateMapWithFilteredIds;
    };
  }, [geoJsonData]);

  // Function to update markers on the map
  const updateMapMarkers = (dataToShow) => {
    const map = mapInstanceRef.current;
    if (!map) return;

    // Remove existing markers cluster group if it exists
    authorLayerRef.current.clearLayers();
    libraryLayerRef.current.clearLayers();

    // DEBUG: Count features by type
    const authorCount = dataToShow.features.filter(
      (f) => f.properties?.type === "author"
    ).length;
    const libraryCount = dataToShow.features.filter(
      (f) => f.properties?.type === "library"
    ).length;
    console.log(
      "Features to plot - Authors:",
      authorCount,
      "Libraries:",
      libraryCount
    );

    // Add markers for filtered data
    dataToShow.features.forEach((feature) => {
      const { geometry, properties } = feature;

      if (
        geometry &&
        geometry.type === "Point" &&
        geometry.coordinates.length === 2 &&
        !isNaN(geometry.coordinates[0]) &&
        !isNaN(geometry.coordinates[1])
      ) {
        // Create a marker with the appropriate icon based on properties.type
        properties.type = properties.type || "author"; // Default to "author" if type is not specified
        const marker = L.marker(
          [geometry.coordinates[1], geometry.coordinates[0]],
          {
            icon: properties.type === "author" ? authorIcon : libraryIcon,
          }
        );
        if (properties) {
          const url = withBasePath(properties.url || "");
          const popupContent = `
                        <div class="map-popup">
                            <h3><a href=${url} class="font-semibold italic text-base underline decoration-dotted underline-offset-2">${
            properties.title || ""
          } </a><br/></h3>
                            <p>Place: ${properties.place || ""} (${
            properties.description
          }) <br/>														
							${properties.author ? `Author: ${properties.author} <br/>` : ""}	
                             ${
                               properties.work
                                 ? `Work: ${properties?.work} <br/>`
                                 : ""
                             }	
							${properties.manuscript ? `MS: ${properties.manuscript} <br/>` : ""}	
							</p> 
                        </div>
                    `;
          marker.bindPopup(popupContent);
        }
        // Add marker to the appropriate layer based on properties.type
        if (properties.type === "author") {
          authorLayerRef.current.addLayer(marker);
        } else if (properties.type === "library") {
          libraryLayerRef.current.addLayer(marker);
        }
      }
    });

    // Fit bounds if there are features
    if (dataToShow.features.length > 0) {
      try {
        const coordinates = dataToShow.features
          .filter((f) => f.geometry && f.geometry.type === "Point")
          .map((f) => [f.geometry.coordinates[1], f.geometry.coordinates[0]]);

        if (coordinates.length > 0) {
          const bounds = L.latLngBounds(coordinates);
          map.fitBounds(bounds, {
            padding: [50, 50],
            maxZoom: 10,
          });
        }
      } catch (error) {
        console.warn("Could not fit bounds:", error);
      }
    }
  };

  useEffect(() => {
    // Initialize map if it doesn't exist yet
    if (!mapInstanceRef.current && mapRef.current) {
      const map = L.map(mapRef.current).setView(initialView, initialZoom);

      // Add OpenStreetMap tiles
      L.tileLayer(
        "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
        {
          attribution:
            '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
          maxZoom: 19,
        }
      ).addTo(map);

      const authorLayer = L.markerClusterGroup({
        spiderfyOnMaxZoom: true, // Enable spiderfy when zoomed in
        showCoverageOnHover: false,
        zoomToBoundsOnClick: true,
        maxClusterRadius: 50,
        // add some offset to avoid overlapping clusters
        iconCreateFunction: (cluster) => {
          const count = cluster.getChildCount();
          const offsetX = Math.random() * 10 - 5;
          const offsetY = Math.random() * 10 - 5;
          return L.divIcon({
            html: `<div class="bg-brand-800 opacity-60 text-white rounded-full w-8 h-8 flex items-center justify-center">${count}</div>`,
            className: "custom-cluster-icon-origin",
            iconSize: [30, 30],
            iconAnchor: [25 + offsetX, 25 + offsetY], // Apply the offset
          });
        },
      });

      const libraryLayer = L.markerClusterGroup({
        spiderfyOnMaxZoom: true, // Enable spiderfy when zoomed in
        showCoverageOnHover: false,
        zoomToBoundsOnClick: true,
        maxClusterRadius: 50,
        iconCreateFunction: (cluster) => {
          const count = cluster.getChildCount();
          const offsetX = Math.random() * 10 + 5;
          const offsetY = Math.random() * 10 + 5;
          return L.divIcon({
            html: `<div class="bg-sage-900 opacity-60 text-white rounded-full w-8 h-8 flex items-center justify-center">${count}</div>`,
            className: "custom-cluster-icon-origin",
            iconSize: [30, 30],
            iconAnchor: [25 + offsetX, 25 + offsetY],
          });
        },
      });

      authorLayerRef.current = authorLayer;
      libraryLayerRef.current = libraryLayer;

      // Add the marker cluster groups to the map
      map.addLayer(authorLayer);
      map.addLayer(libraryLayer);

      // Add layer control if types are present i.e. more than one layer

      // Check if there are features with defined types
      const hasAuthorType = geoJsonData.features.some(
        (f) => f.properties?.type === "author"
      );
      const hasLibraryType = geoJsonData.features.some(
        (f) => f.properties?.type === "library"
      );

      // Only add layer control if we have both types
      if (hasAuthorType && hasLibraryType) {
        L.control
          .layers(
            {},
            {
              Authors: authorLayer,
              Manuscripts: libraryLayer,
            },
            { collapsed: false }
          )
          .addTo(map);
      }
      // Store map instance for cleanup
      mapInstanceRef.current = map;
    }

    // Initial load of all data
    updateMapMarkers(geoJsonData);

    // Cleanup function
    return () => {
      if (mapInstanceRef.current) {
        mapInstanceRef.current.remove();
        mapInstanceRef.current = null;
      }

      authorLayerRef.current = null;
      libraryLayerRef.current = null;
    };
  }, [geoJsonData, initialView, initialZoom, markerColor]);

  return <div ref={mapRef} className={className} id="leaflet-map"></div>;
}
